### ISSUE TITLE
Fix your license

### ISSUE THREAD

**Issue by Yetoo1** [thephoenixprojectsoftware/ApexCMD#1]
The LICENSE file says this is under the GPL (with no exemptions or exceptions for what you want to do by the way) yet the readme says that you need to contact you to sell it. Whatever license you're trying to sub license as in the readme or the other way around is incompatible with GPL. You can instead say that if one wishes to obtain a license which permits selling the executable without needing to provide source code, that would work. The aforementioned dual licensing situation is actually enforceable. I'm not a lawyer.

**Comment by sabianroberts** [comment]
### Problem solved, issue closed
I have notified the team at The Phoenix Project, and they have updated the License and updated the README.md, thank you for notifying us. I have now closed this issue
